### ISSUE TITLE
redirect to latest version

### ISSUE THREAD

**Issue by mfulton26** [denoland/docland#38]
I released a new version of my code but docland didn't pick it up yet when I visit the URL without a version in it. It'd be nice to have it auto-redirect to the latest version whenever someone navigates to the URL without a version in it.

e.g. https://doc.deno.land/https://deno.land/x/xnd/_index.ts → https://doc.deno.land/https://deno.land/x/xnd@v2.1.3/_index.ts (currently)

**Comment by kitsonk** [comment]
The doc website, per instance, caches the documentation in memory, so it takes a while for it to purge.

That being said, when the doc website gets directed on the URL being supplied, it bubble the redirect up to the doc URL, which in this case would do what is suggested here.  It is a little complex, because currently we just hand the URL over to `deno_doc` and don't fetch it initially.  Certainly worth considering.
