### ISSUE TITLE
timeouts failing when doc-ing excessively large libraries

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/docland#49]
I'm always getting this when trying to load [docs from this URL: https://code.harmony.rocks/v2.4.0](https://doc.deno.land/https://code.harmony.rocks/v2.4.0) (or from the https://deno.land/x/harmony module in general):

![image](https://user-images.githubusercontent.com/43033058/146669674-39fd894c-d843-40a1-b64c-6ab2c0925b6e.png)

**Comment by kitsonk** [comment]
It is timing out on Deploy.

This is in part due to https://github.com/denoland/deno_graph/pull/89 but also this particular library has a _huge_ dependency graph.  On a local instance it is taking 29-33 seconds to render the doc, it has 1251 dependencies, 236 unique.

(Comparatively, oak takes ~3 seconds, @firebase/firestore ~3 seconds, preact ~1.1 seconds, so it is 10x longer than other fairly complex libraries)

I will try tomorrow with the deno_graph patch and see how much that speeds things up by, but there maybe just some things that are going to be hard to doc "on the fly".

**Comment by kitsonk** [comment]
Ok, using the patched versions of deno_graph/deno_doc takes it from ~30 seconds to ~8.5 seconds, still pretty heafty.  oak goes from ~3 seconds to ~2.3 seconds, so the patch helps quite a bit.

Once everything gets merged and published, I will check again to see if the timeouts still occur.

**Comment by kitsonk** [comment]
I am not getting the timeout anymore.
