### ISSUE TITLE
single docs page for multiple modules

### ISSUE THREAD

**Issue by mfulton26** [denoland/docland#66]
I'd like to be able to have a single docs page for all my many modules in my repository. I currently use a `_index.ts` (I suppose I could name it `_mod.ts` instead). This works fine but I'm wondering if there might be a different way to do this that doesn't involve create a private/internal module that creates a directory of all my other modules manually.

e.g. could support be added to use some kind of pattern glob or something similar?

**Comment by kitsonk** [comment]
I'm not personally too sure, as it makes the whole model very complicated, as it is designed to be a per module doc generator. Just globbing would start to force arbitrary semantics, like what is a "private" and what is a "public" module.

Since you can't glob imports, then the one to one relationship of importable item to top level doc page makes sense, as anything else would need additional context, like to do X import Y. The end user creating a README that provides that context and links to individual module pages would make a lot more sense to me.

**Comment by mfulton26** [comment]
Okay, that makes sense. I figured out wouldn't hurt to ask and explore. I love them idea of a README as a directory. It seems a little bit of manual maintenance but I suppose that could be automated without too much trouble. Thanks.
